### ISSUE TITLE
Attribute drag-end do not work properly

### ISSUE THREAD

**Issue by Gitek1** [Boulevard/sortable#2]

**Comment by daniel-nagy** [comment]
@Gitek1 can you provide more information?

**Comment by jackdclick** [comment]
I'm getting the same.  I put dragEnd="my controller function" on the tbody and its never fired.

`tbody class="items" md-body sortable ng-model="rules.workflowList" options="rules.workflowOrderOptions" dragEnd="rules.workflowDragEnd()">`

`workflowDragEnd() {
        console.log('in here');
    }`

**Comment by daniel-nagy** [comment]
@jackdclick Your syntax is slightly off, should be

```html
<tbody drag-end="rules.workflowDragEnd">
```

**Comment by daniel-nagy** [comment]
I added an example of using drag events to the docs, [Usage](https://github.com/Boulevard/sortable#usage).

**Comment by jackdclick** [comment]
@daniel-nagy Thanks for the quick response!  I knew it was probably syntax.  Cheers, love the module.
